#includepath "/d/Google Drive/Adobe Scripting/as_snippets/lib/file";
#include "as_checkSecurityPrefSet.jsxinc";
#include "as_fileRead.jsxinc";
#include "as_fileReadJSBinary.jsxinc";
#include "as_fileReadJSON.jsxinc";
#include "as_fileToBinaryString.jsxinc";
#include "as_fileWrite.jsxinc";
#include "as_fileWriteJSBinary.jsxinc";
#include "as_fileWriteJSON.jsxinc";
#include "as_getFileExtension.jsxinc";
#include "as_getFileName.jsxinc";
#include "as_getTempFolder.jsxinc";
#include "as_getUserDataFolder.jsxinc";
#include "as_PNGFilesToJSON.jsxinc";